version: '3'
services:
  service1:
    build:
      context: ./service1/
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
    networks:
      - default
  service2:
    build:
      context: ./service2/
      dockerfile: Dockerfile
    networks:
      - default
  